apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspapp-deployment
  labels:
    app: aspapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspapp
  template:
    metadata:
      labels:
        app: aspapp
    spec:
      containers:
      - name: aspapp
        image: samples/aspnetapp:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: my-image-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: aspapp
  name: aspapp-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: aspapp