apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspapp-deployment
  labels:
    app: aspapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspapp
  template:
    metadata:
      labels:
        app: aspapp
    spec:
      containers:
      - name: aspapp
        image: acrtest989.azurecr.io/samples/aspnetapp:latest
        ports:
        - containerPort: 80
      magePullSecrets:
      - name: acrtest989-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: aspapp
  name: aspapp-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: aspapp
---
apiVersion: v1
kind: Secret
metadata:
  name: acrtest989-secret
data:
  username: default-token-fmqpf
  password: epoxnNlnA=j6+UbLpLKKe/Fa5e2oD0Bv