apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspapp
  template:
    metadata:
      labels:
        app: aspapp
    spec:
      containers:
      - name: aspapp
        image: acrtest987.azurecr.io/samples/aspnetapp:0.1
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: aspapp
  name: aspapp-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: aspapp