apiVersion: v1
kind: Service
metadata:
  labels:
    app: samples-aspnetapp
  name: aspnetapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: samples-aspnetapp