apiVersion: apps/v1
kind: Deployment
metadata:
  name: samples-aspnetapp
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: samples-aspnetapp
    spec:
      nodeSelector:
        'beta.kubernetes.io/os': nodepool1
      containers:
      - name: aspnetapp
        image: acrtest989.azurecr.io/samples/aspnetapp:latest
        resources: {}
        env:
        - name: PORT
          value: '4000'
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: samples-aspnetapp
  name: aspnetapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: samples-aspnetapp