apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspapp-deployment
  labels:
    app: aspapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspapp0
  template:
    metadata:
      labels:
        app: aspapp0
    spec:
      containers:
      - name: aspapp
        image: acrtest989.azurecr.io/samples/aspnetapp:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: testsecret