apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspapp
  template:
    metadata:
      labels:
        app: aspapp
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: aspapp
        image: ${Repository}/${AppImageName}:${TAG}
        ports:
        - containerPort: 80
        env:
        - name: Repository
          value: "acr987.azurecr.io"
        - name: AppImageName
          value: "samples/aspnetapp"
        - name: TAG
          value: "0.1"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: aspapp
  name: aspapp-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: aspapp