apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspapp
  template:
    metadata:
      labels:
        app: aspapp
    spec:
      containers:
      - name: aspapp
        image: acrtest989.azurecr.io/samples/aspnetapp:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 1000m
            cpu: "1"
          limits:
            memory: 1000m
            cpu: "1"
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: aspapp
  name: aspapp-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: aspapp