apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${AppName}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${AppName}
  template:
    metadata:
      labels:
        app: ${AppName}
    spec:
      containers:
      - name: ${AppName}
        image: ${Repository}/${AppImageName}:${TAG}
        ports:
        - containerPort: ${InPort}
      imagePullSecrets:
      - name: acr-secret
      env:
      - name: AppName
        value: "aspapp"
      - name: Repository
        value: "acr987.azurecr.io"
      - name: AppImageName
        value: "samples/aspnetapp"
      - name: TAG
        value: "0.1"
      - name: InPort
        value: "80"
      - name: TargetPort
        type: integer
        value: "80"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${AppName}
  name: ${AppName}-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: ${InPort}
      targetPort: ${TargetPort}
  selector:
    app: ${AppName}