apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetapp
spec:
  replicas: 1
  selector:
    matchLabels:
     name: aspnetapp
  strategy: {}
  template:
    metadata:
      labels:
        app: aspnetapp
    spec:
      containers:
      - name: aspnetapp
        image: acrtest989.azurecr.io/samples/aspnetapp:latest
        resources: {}
        env:
        - name: PORT
          value: '5000'