apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-worker
  template:
    metadata:
      labels:
        app: main-worker
    spec:
      containers:
      - name: main-worker
        image: acrtest989.azurecr.io/samples/aspnetapp:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 2000m
            cpu: "1"
          limits:
            memory: 2000m
            cpu: "1"
      imagePullSecrets:
      - name: acr-secret