apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspapp
  template:
    metadata:
      labels:
        app: aspapp
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: aspapp
        image: acr987.azurecr.io/samples/aspnetapp:0.1
        ports:
        - containerPort: 80
        env:
        - name: REPOSITORY
          value: "acr987.azurecr.io/"
        - name: APP_IMAGE_NAME
          value: "samples/aspnetapp:"
        - name: TAG
          value: "0.1"
        command: ["echo"]
        args: ["$(REPOSITORY) $(APP_IMAGE_NAME) $(TAG)"]
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: aspapp
  name: aspapp-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: aspapp